Fix vite manifest not found
YunoHost-Apps/lychee_ynh pull request #135
Opened 2024-12-05 17:29 UTC by DeMiro5001

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2024-12-05 17:31 UTC, DeMiro5001 commented
!testme

2024-12-05 20:59 UTC, DeMiro5001 commented
!testme

2024-12-06 07:53 UTC, DeMiro5001 commented
!testme

2024-12-07 03:15 UTC, DeMiro5001 commented
!testme

2024-12-07 08:24 UTC, ericgaspar requested changes

2024-12-07 08:24 UTC, ericgaspar commented on scripts/install
> +         npm run build 2>&1
```suggestion
	 ynh_hide_warnings npm install
         ynh_hide_warnings npm run build
```

2024-12-07 08:24 UTC, ericgaspar commented on scripts/upgrade
> +         npm run build 2>&1
```suggestion
         ynh_hide_warnings npm install
         ynh_hide_warnings npm run build
```

2024-12-07 08:24 UTC, ericgaspar commented on scripts/_common.sh
> +nodejs_version=22
```suggestion
nodejs_version="22"
```

2024-12-07 09:03 UTC, DeMiro5001 commented
!testme

2024-12-07 14:02 UTC, orhtej2 commented
While this very likely gets Lychee running these steps are performed on their CI already, I feel like changing the source artifact to `Lychee.zip` instead of tag tarball would get the app up and running.

2024-12-07 14:07 UTC, orhtej2 commented
Testing here: #136

2024-12-07 20:25 UTC, DeMiro5001 commented
> While this very likely gets Lychee running these steps are performed on their CI already, I feel like changing the source artifact to `Lychee.zip` instead of tag tarball would get the app up and running.

I prefer your solution. And it takes less time according to bullseye Ci (since it runs one job at a time, so other jobs won't slow it).

2024-12-08 12:44 UTC, orhtej2 commented
Superseded by #136

2024-12-08 12:44 UTC, closed without merging